### ISSUE TITLE
Can't replace null environment variable via CLI

### ISSUE THREAD

**Issue by reesehopkins** [ploomber/ploomber#1024]
I have an `env.yaml` with a null value that I want to occasionally overwrite via the `ploomber build` CLI command. But I get a `KeyError: 'Trying to replace key "null_variable" in env, but it does not exist'` error. Here's a reproducible example.

### pipeline.yaml

```yaml
tasks:
  - source: get.py
    product:
      nb: get.ipynb
    params:
      str_variable: '{{str_variable}}'
      null_variable: '{{null_variable}}'
```

### env.yaml

```yaml
str_variable: A
null_variable: null
```

### get.py

```python
# + tags=["parameters"]
upstream = None
product = None
str_variable = None
null_variable = None
# -

print(str_variable)

print(null_variable)

```

### stacktrace

Running `ploomber build --env--null_variable ABC` results in the following stack trace:

```python
Traceback (most recent call last):
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/site-packages/ploomber/cli/io.py", line 54, in wrapper
    fn(**kwargs)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/site-packages/ploomber_core/telemetry/telemetry.py", line 529, in wrapper
    raise e
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/site-packages/ploomber_core/telemetry/telemetry.py", line 515, in wrapper
    result = func(_payload, *args, **kwargs)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/site-packages/ploomber/cli/build.py", line 63, in main
    dag, args = parser.load_from_entry_point_arg()
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/site-packages/ploomber/cli/parsers.py", line 222, in load_from_entry_point_arg
    dag, args = load_dag_from_entry_point_and_parser(
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/site-packages/ploomber/cli/parsers.py", line 495, in load_dag_from_entry_point_and_parser
    dag, args = _process_file_dir_or_glob(parser)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/site-packages/ploomber/cli/parsers.py", line 446, in _process_file_dir_or_glob
    env = env_dict._replace_flatten_keys(replaced)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/site-packages/ploomber/env/envdict.py", line 310, in _replace_flatten_keys
    obj._inplace_replace_flatten_keys(to_replace)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/site-packages/ploomber/env/envdict.py", line 306, in _inplace_replace_flatten_keys
    self._inplace_replace_flatten_key(value, key)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/site-packages/ploomber/env/envdict.py", line 293, in _inplace_replace_flatten_key
    self._replace_value(value, keys_all)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/site-packages/ploomber/env/envdict.py", line 267, in _replace_value
    raise KeyError('Trying to replace key "{}" in env, '
KeyError: 'Trying to replace key "null_variable" in env, but it does not exist'
```

**Comment by edublancas** [comment]
thanks for reporting this. fixed! this will be out in our next release!
