### ISSUE TITLE
nb inject fails when using ploomber scaffolding for a package

### ISSUE THREAD

**Issue by NKeleher** [ploomber/ploomber#1048]
When using the [ploomber scaffolding for a package](https://docs.ploomber.io/en/latest/user-guide/scaffold.html#packaging-projects) my attempts to run ploomber nb --inject result in the following error:

```
Traceback (most recent call last):
  File "path-to-venv/venv/lib/python3.9/site-packages/ploomber/cli/io.py", line 103, in wrapper
    fn(**kwargs)
  File "path-to-venv/venv/lib/python3.9/site-packages/ploomber_core/telemetry/telemetry.py", line 545, in wrapper
    raise e
  File "path-to-venv/venv/lib/python3.9/site-packages/ploomber_core/telemetry/telemetry.py", line 533, in wrapper
    result = func(*args, **kwargs)
  File "path-venv/venv/lib/python3.9/site-packages/ploomber/cli/nb.py", line 472, in main
    params_to_inject, warning_message, exceptions = _get_params_to_inject(
  File "path-to-venv/venv/lib/python3.9/site-packages/ploomber/cli/nb.py", line 132, in _get_params_to_inject
    unprioritized_tasks_to_inject, warning_message = _get_tasks_to_inject(
  File "path-to-venv/venv/lib/python3.9/site-packages/ploomber/cli/nb.py", line 84, in _get_tasks_to_inject
    full_template_name = Path(task.source._path).name
AttributeError: 'PythonCallableSource' object has no attribute '_path'
```

Reprex:
```
> ploomber scaffold --package
...
> ploomber install
...
> ploomber nb --inject
```

**Comment by edublancas** [comment]
We just merged a fix. This will be in our next release!
