### ISSUE TITLE
ValueError: invalid width -1 (must be > 0)

### ISSUE THREAD

**Issue by oguiza** [ploomber/ploomber#1079]
I've built 3 pipelines using the Python API as part of a GitHub repository. I've tried to run the pipelines in Google Colab cloning the repository. Everything works fine, but once the pipeline finishes I get this error:
```bash
/usr/local/lib/python3.8/dist-packages/ploomber/table.py:353: UserWarning: Not enough space to display 1 columns with a width of -43. Using a column width of 1
  warn(f'Not enough space to display {n_cols} columns with '
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ploomber/cli/io.py", line 53, in wrapper
    fn(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ploomber_core/telemetry/telemetry.py", line 743, in wrapper
    result = func(_payload, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ploomber/cli/build.py", line 96, in main
    report = dag.build(force=args.force, debug=debug)
  File "/usr/local/lib/python3.8/dist-packages/ploomber/dag/dag.py", line 550, in build
    report = callable_()
  File "/usr/local/lib/python3.8/dist-packages/ploomber/dag/dag.py", line 609, in _build
    self._logger.info(' DAG report:\n{}'.format(build_report))
  File "/usr/local/lib/python3.8/dist-packages/ploomber/table.py", line 99, in __str__
    values = wrap_table_dict(self._values, self.column_width,
  File "/usr/local/lib/python3.8/dist-packages/ploomber/table.py", line 246, in wrap_table_dict
    return apply_wrapping(table_dict, wrapper, exclude=exclude)
  File "/usr/local/lib/python3.8/dist-packages/ploomber/table.py", line 366, in apply_wrapping
    return dict(
  File "/usr/local/lib/python3.8/dist-packages/ploomber/table.py", line 367, in <genexpr>
    apply_wrapping_to_column(header, values, exclude, wrapper)
  File "/usr/local/lib/python3.8/dist-packages/ploomber/table.py", line 392, in apply_wrapping_to_column
    header_wrapped = wrap_elementwise(header, _wrapper)
  File "/usr/local/lib/python3.8/dist-packages/ploomber/table.py", line 403, in wrap_elementwise
    return wrapper.fill(str(value))
  File "/usr/lib/python3.8/textwrap.py", line 363, in fill
    return "\n".join(self.wrap(text))
  File "/usr/lib/python3.8/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/usr/lib/python3.8/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -1 (must be > 0)
```
I'm using ploomber==0.22.2.
Please, let me know if you need any more details on the issue.

**Comment by oguiza** [comment]
```bash
https://colab.research.google.com/gist/oguiza/d6332bedeaf83b602bfebbab9021de35/scratchpad.ipynb
```

**Comment by edublancas** [comment]
I tried running the notebook, but GitHub failed (I passed a token, but it said I don't have write permissions).

Seem like there's a [bug](https://bugs.python.org/msg144947) in the textwrap library from Python

I found that people suggest creating an [environment variable](https://stackoverflow.com/a/63683357/709975), can you give it a try and let me know if it works?

**Comment by oguiza** [comment]
Thanks Eduardo! 
Good finding! I've tested your proposed solution (setting `os.environ["COLUMNS"] = "79"`) and that fixes the issue.
