### ISSUE TITLE
Error when replacing file on Windows

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#333]
```pytb
====================================================== DAG build failed ======================================================
----- NotebookRunner: fit -> MetaProduct({'model': File('products\\model.pickle'), 'nb': File('products\\report.html')}) -----
----------------------------------------- C:\Users\edubl\Desktop\proj\scripts\fit.py -----------------------------------------
Traceback (most recent call last):
  File "c:\users\edubl\desktop\proj\venv-proj\lib\site-packages\ploomber\tasks\abc.py", line 562, in _build
    res = self._run()
  File "c:\users\edubl\desktop\proj\venv-proj\lib\site-packages\ploomber\tasks\abc.py", line 669, in _run
    self.run()
  File "c:\users\edubl\desktop\proj\venv-proj\lib\site-packages\ploomber\tasks\notebook.py", line 524, in run
    path_to_out_ipynb.rename(path_to_out)
  File "C:\Users\edubl\miniconda3\envs\scaffold\lib\pathlib.py", line 1359, in rename
    self._accessor.rename(self, target)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\edubl\\Desktop\\proj\\products\\report.ipynb' -> 'C:\\Users\\edubl\\Desktop\\proj\\products\\report.html'

The above exception was the direct cause of the following exception:
```

**Comment by edublancas** [comment]
I encounter this when fixing another Windows bug, unfortunately, I don't have a Windows machine right now but I think you can reproduce it with this:

1. install ploomber
2. Download this example https://github.com/ploomber/projects/tree/master/spec-api-python
3. Change the pipeline.yaml file, line 18 for output/plot.html https://github.com/ploomber/projects/blob/33122dd49acd47c0b5370921f6d6574a4693c0c5/spec-api-python/pipeline.yaml#L13
4. Run "ploomber build" in the directory that has the pipeline.yaml
5. Run "ploomber build" again

Let me know if the error appears

**Comment by idomic** [comment]
@Harsh-1309 any update there?
