### ISSUE TITLE
Changes to scripts and notebooks static analysis

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#336]
This issue discusses the implementation of a feature that performs code checks on scripts and notebooks. Although this feature has been there for a while, it's turned off by default. We'll introduce changes on its functionality on version `0.13` and turn it on by default on version `0.13.1`.

## Changes

1. `0.13`
    1.  Keep the feature off by default. When turned on, it will raise an exception (instead of a warning) when missing parameters (e.g., parmeters declare some parameter but `pipeline.yaml` does not have it)
    2. Display a warning `"static_analysis default value will change to True"`
2. `0.13.1`
    1. Set the default value to True

## Motivation

Scripts and notebooks execute cell-by-cell; the Python interpreter does not get the code all at once but chunks of it. Which causes files with errors to execute partially, instead of aborting execution from the beginning. Example:

```python
# Cell 1 - executes normally
1 + 1

# Cell 2 - breaks, since x is undefined
x
```

This is frustrating when executing long-running processes, as silly mistakes can break execution, and we have to start over again.

A second issue is script/notebook parametrization. Say a notebook is parametrized like this:

```yaml
tasks:
    - source: script.py
      product: out.html
      # pass custom parameters
      params:
        some_param: value
```

During execution, Ploomber injects:

```python
some_param = 'value'
```

However, there isn't any validation done; a user may have a typo, and Ploomber won't complain. This enhancement makes scripts and notebooks behave more like functions by extracting a "signature" from the parameters cell, for example:

```python
# + tags=["parameters"]
param = None
```

Through the "parameters" cell, this script states that it needs an argument "param", if not passed, it will report an error before execution.

**This implies that scripts and notebooks must list their arguments in the parameters cell and the passed arguments in `params` (in the `pipeline.yaml`) file must match.**

## Examples

**Script with an undefined variable**: `df_` is used in the script but never assigned a value

```pytb
================================== DAG render failed ==================================
- NotebookRunner: fit -> MetaProduct({'model': File('products/model.pickle'), 'nb': File('products/report.ipynb')}) -
--------------------------- /Users/Edu/proj/scripts/fit.py ----------------------------
Traceback (most recent call last):
  File "/Users/Edu/dev/ploomber/src/ploomber/dag/dag.py", line 373, in _render_current
    t.render(
  File "/Users/Edu/dev/ploomber/src/ploomber/tasks/abc.py", line 737, in render
    raise e
  File "/Users/Edu/dev/ploomber/src/ploomber/tasks/abc.py", line 734, in render
    self.source.render(self.params)
  File "/Users/Edu/dev/ploomber/src/ploomber/sources/notebooksource.py", line 159, in render
    self._render()
  File "/Users/Edu/dev/ploomber/src/ploomber/sources/notebooksource.py", line 180, in _render
    self._post_render_validation(self._params, self._nb_str_rendered)
  File "/Users/Edu/dev/ploomber/src/ploomber/sources/notebooksource.py", line 254, in _post_render_validation
    check_notebook(nb, params, filename=self._path or 'notebook')
  File "/Users/Edu/dev/ploomber/src/ploomber/static_analysis/pyflakes.py", line 138, in check_notebook
    check_source(nb)
  File "/Users/Edu/dev/ploomber/src/ploomber/static_analysis/pyflakes.py", line 157, in check_source
    reporter._check()
  File "/Users/Edu/dev/ploomber/src/ploomber/static_analysis/pyflakes.py", line 108, in _check
    raise RenderError(errors)
ploomber.exceptions.RenderError: :29:1 undefined name 'df_'
================================== Summary (1 task) ===================================
NotebookRunner: fit -> MetaProduct({'model': File('products/model.pickle'), 'nb': File('products/report.ipynb')})
================================== DAG render failed ==================================
```

**Script with an unexpected parameter:** `pipeline.yaml` passed a param `arg` to the task, but the task's parameters cell does declare such parameter

```pytb
================================== DAG render failed ==================================
- NotebookRunner: fit -> MetaProduct({'model': File('products/model.pickle'), 'nb': File('products/report.ipynb')}) -
--------------------------- /Users/Edu/proj/scripts/fit.py ----------------------------
Traceback (most recent call last):
  File "/Users/Edu/dev/ploomber/src/ploomber/dag/dag.py", line 373, in _render_current
    t.render(
  File "/Users/Edu/dev/ploomber/src/ploomber/tasks/abc.py", line 737, in render
    raise e
  File "/Users/Edu/dev/ploomber/src/ploomber/tasks/abc.py", line 734, in render
    self.source.render(self.params)
  File "/Users/Edu/dev/ploomber/src/ploomber/sources/notebooksource.py", line 159, in render
    self._render()
  File "/Users/Edu/dev/ploomber/src/ploomber/sources/notebooksource.py", line 180, in _render
    self._post_render_validation(self._params, self._nb_str_rendered)
  File "/Users/Edu/dev/ploomber/src/ploomber/sources/notebooksource.py", line 254, in _post_render_validation
    check_notebook(nb, params, filename=self._path or 'notebook')
  File "/Users/Edu/dev/ploomber/src/ploomber/static_analysis/pyflakes.py", line 139, in check_notebook
    check_params(params, params_cell['source'], filename)
  File "/Users/Edu/dev/ploomber/src/ploomber/static_analysis/pyflakes.py", line 178, in check_params
    raise TypeError(
TypeError: Error rendering notebook '/Users/Edu/proj/scripts/fit.py', parameters declared in the 'parameters' cell do not match task params: Unexpected params: 'arg'
================================== Summary (1 task) ===================================
NotebookRunner: fit -> MetaProduct({'model': File('products/model.pickle'), 'nb': File('products/report.ipynb')})
================================== DAG render failed ==================================
```

**Comment by mitch-at-orika** [comment]
Haha I hated this analysis untill I just read why you made me fix them all in my code! I definetely want it to warn me of breaks in the future so worth the effort now! It is a pretty fast general code check / debugging loop anyway. Also... I better clean up my act in those notebooks!
