### ISSUE TITLE
Jupyter Notebook raises CallbackCheckAborted if DAG-level on_render specified

### ISSUE THREAD

**Issue by rdmolony** [ploomber/ploomber#351]
Hi there,

This is a weird one.  It occurs when trying to open a notebook in Jupyter Lab in the same directory as a `pipeline.yaml` with a DAG-level `on_render` hook.  

You can reproduce it by ...

```
pip install ploomber codema-dev-tasks==0.2.0
```

> We don't need `codema-dev-tasks` to reproduce - I've just specified this for a convenient DAG level hook and download task

 ... specifying a `pipeline.yaml` like ...

```yaml
on_render:
  dotted_path: codema_dev_tasks.hooks.load_environmental_variables
  dotenv_path: ".env"

tasks:
  - source: codema_dev_tasks.requests.fetch_file
    name: download_county_residential_networked_gas_consumption
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/views/2021_09_23_county_residential_networked_gas_consumption.csv
    product: data/external/2021_09_23_county_residential_networked_gas_consumption.csv
```
... and then try to create a new notebook in the same directory

This yields the GUI error of ...
```
File Load Error for Untitled.ipynb
Unhandled error
```
... and the Command Line error of ...

```python-traceback
[I 2021-10-06 14:24:41.837 ServerApp] [Ploomber] Requested model: test/Untitled.ipynb. Looking for DAG with root dir: /home/wsl-rowanm/code-wsl/codema-dev-projects
Exception when running on_render for DAG "No name": Cannot check callback because function is a dotted path whose function has not been imported yet
Traceback (most recent call last):
  File "/home/wsl-rowanm/mambaforge/envs/codema-dev-projects/lib/python3.8/site-packages/ploomber/dag/dag.py", line 397, in _render_current
    self._run_on_render()
  File "/home/wsl-rowanm/mambaforge/envs/codema-dev-projects/lib/python3.8/site-packages/ploomber/dag/dag.py", line 628, in _run_on_render
    kwargs = callback_check(self.on_render, kwargs_available)
  File "/home/wsl-rowanm/mambaforge/envs/codema-dev-projects/lib/python3.8/site-packages/ploomber/util/util.py", line 143, in callback_check
    raise CallbackCheckAborted(
ploomber.exceptions.CallbackCheckAborted: Cannot check callback because function is a dotted path whose function has not been imported yet
[E 2021-10-06 14:24:41.851 ServerApp] Uncaught exception GET /api/contents/test/Untitled.ipynb?type=notebook&content=1&1633526679992 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/test/Untitled.ipynb?type=notebook&content=1&1633526679992', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/wsl-rowanm/mambaforge/envs/codema-dev-projects/lib/python3.8/site-packages/ploomber/dag/dag.py", line 397, in _render_current
        self._run_on_render()
      File "/home/wsl-rowanm/mambaforge/envs/codema-dev-projects/lib/python3.8/site-packages/ploomber/dag/dag.py", line 628, in _run_on_render
        kwargs = callback_check(self.on_render, kwargs_available)
      File "/home/wsl-rowanm/mambaforge/envs/codema-dev-projects/lib/python3.8/site-packages/ploomber/util/util.py", line 143, in callback_check
        raise CallbackCheckAborted(
    ploomber.exceptions.CallbackCheckAborted: Cannot check callback because function is a dotted path whose function has not been imported yet
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/wsl-rowanm/mambaforge/envs/codema-dev-projects/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/home/wsl-rowanm/mambaforge/envs/codema-dev-projects/lib/python3.8/site-packages/jupyter_server/services/contents/handlers.py", line 106, in get
        self.contents_manager.get(
      File "/home/wsl-rowanm/mambaforge/envs/codema-dev-projects/lib/python3.8/site-packages/ploomber/jupyter/manager.py", line 244, in get
        self.load_dag(
      File "/home/wsl-rowanm/mambaforge/envs/codema-dev-projects/lib/python3.8/site-packages/ploomber/jupyter/manager.py", line 163, in load_dag
        self.dag.render(force=True, show_progress=False)
      File "/home/wsl-rowanm/mambaforge/envs/codema-dev-projects/lib/python3.8/site-packages/ploomber/dag/dag.py", line 336, in render
        self._render_current(force=force,
      File "/home/wsl-rowanm/mambaforge/envs/codema-dev-projects/lib/python3.8/site-packages/ploomber/dag/dag.py", line 404, in _render_current
        raise DAGRenderError(msg) from e
    ploomber.exceptions.DAGRenderError: Exception when running on_render for DAG "No name": Cannot check callback because function is a dotted path whose function has not been imported yet
[W 2021-10-06 14:24:41.852 ServerApp] Unhandled error
[E 2021-10-06 14:24:41.855 ServerApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0",
      "Accept": "*/*",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/lab/workspaces/auto-s/tree/test/pipeline.yaml",
      "Authorization": "token 70822a15cd3e2449fce28823a50ed0f0c8d9fafc44800459",
      "X-Xsrftoken": "2|d36529b1|96602ba849619f820751819b810fbdb0|1633357752",
      "Content-Type": "application/json",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1633526680|23:username-localhost-8888|44:MWM3OTQwYjYzOTE0NDNjMjkzNjg5NGMzNDU5NThkODM=|0d843e2d34b81084214387397679535f37009ed188d18596b2d119b653864eea\"; _xsrf=2|d36529b1|96602ba849619f820751819b810fbdb0|1633357752",
      "Sec-Fetch-Dest": "empty",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Site": "same-origin",
      "Dnt": "1",
      "Sec-Gpc": "1",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 2021-10-06 14:24:41.857 ServerApp] 500 GET /api/contents/test/Untitled.ipynb?type=notebook&content=1&1633526679992 (127.0.0.1) 79.20ms referer=http://localhost:8888/lab/workspaces/auto-s/tree/test/pipeline.yaml
```

---

I've gotten around it by adding the `dotenv_path` parameter to `codema_dev_tasks.requests.fetch_file` to load credentials prior to attempting a download [here](https://github.com/codema-dev/tasks)

**Comment by edublancas** [comment]
I fixed this, this will be part of the next release (coming up in a few days)

note that dag-level hooks are not executed when you open files in Jupyter, but I'm guessing that's not a problem in your use case. I'll add a note to the docs

**Comment by rdmolony** [comment]
Great, fair play! My use case was running ploomber build from the README.md of each project via jupytext - initialising env vars is done within each download task rather than DAG level so this is no longer an issue
