### ISSUE TITLE
Better error message when missing __init__.py

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#392]
If a dotted path fails to import, we should check if the reason is a missing `__init__.py` file and suggest adding it. Current error:

```pytb
Traceback (most recent call last):
  File "/Users/Edu/miniconda3/envs/ml-testing/lib/python3.9/site-packages/ploomber/cli/io.py", line 20, in wrapper
    fn(**kwargs)
  File "/Users/Edu/miniconda3/envs/ml-testing/lib/python3.9/site-packages/ploomber/cli/task.py", line 34, in main
    dag, args = _custom_command(parser)
  File "/Users/Edu/miniconda3/envs/ml-testing/lib/python3.9/site-packages/ploomber/cli/parsers.py", line 405, in _custom_command
    dag, args = load_dag_from_entry_point_and_parser(entry_point, parser,
  File "/Users/Edu/miniconda3/envs/ml-testing/lib/python3.9/site-packages/ploomber/cli/parsers.py", line 451, in load_dag_from_entry_point_and_parser
    dag, args = _process_file_dir_or_glob(parser)
  File "/Users/Edu/miniconda3/envs/ml-testing/lib/python3.9/site-packages/ploomber/cli/parsers.py", line 392, in _process_file_dir_or_glob
    dag = DAGSpec(dagspec_arg).to_dag()
  File "/Users/Edu/miniconda3/envs/ml-testing/lib/python3.9/site-packages/ploomber/spec/dagspec.py", line 424, in to_dag
    dag = self._to_dag()
  File "/Users/Edu/miniconda3/envs/ml-testing/lib/python3.9/site-packages/ploomber/spec/dagspec.py", line 473, in _to_dag
    process_tasks(dag, self, root_path=self._parent_path)
  File "/Users/Edu/miniconda3/envs/ml-testing/lib/python3.9/site-packages/ploomber/spec/dagspec.py", line 745, in process_tasks
    task, up = task_dict.to_task(dag)
  File "/Users/Edu/miniconda3/envs/ml-testing/lib/python3.9/site-packages/ploomber/spec/taskspec.py", line 298, in to_task
    return _init_task(data=data,
  File "/Users/Edu/miniconda3/envs/ml-testing/lib/python3.9/site-packages/ploomber/spec/taskspec.py", line 381, in _init_task
    task.on_finish = dotted_path.DottedPath(on_finish,
  File "/Users/Edu/miniconda3/envs/ml-testing/lib/python3.9/site-packages/ploomber/util/dotted_path.py", line 47, in __init__
    self._load_callable()
  File "/Users/Edu/miniconda3/envs/ml-testing/lib/python3.9/site-packages/ploomber/util/dotted_path.py", line 54, in _load_callable
    self._callable = load_callable_dotted_path(self._spec.dotted_path)
  File "/Users/Edu/miniconda3/envs/ml-testing/lib/python3.9/site-packages/ploomber/util/dotted_path.py", line 169, in load_callable_dotted_path
    loaded_object = load_dotted_path(dotted_path=dotted_path,
  File "/Users/Edu/miniconda3/envs/ml-testing/lib/python3.9/site-packages/ploomber/util/dotted_path.py", line 128, in load_dotted_path
    module = importlib.import_module(mod)
  File "/Users/Edu/miniconda3/envs/ml-testing/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: An error happened when trying to import dotted path "tests.quality.clean": No module named 'tests.quality'
```

**Comment by edublancas** [comment]
Sure! Feel free to [reach out to us on Slack](http://community.ploomber.io/) if you have questions.

A few tips to get started:

* Check out our [contributing guide](https://github.com/ploomber/ploomber/blob/master/CONTRIBUTING.md)
* [Here's the line](https://github.com/ploomber/ploomber/blob/702c46d47ee46ce903619e75d3d3c5287a2ebef4/src/ploomber/util/dotted_path.py#L129) that needs the fix
* [Please add tests here](https://github.com/ploomber/ploomber/blob/master/tests/util/test_dotted_path.py)

Essentially, once we detect the `ImportError`, we want to see if the module is importable, but there's an `__init__.py` missing.
