### ISSUE TITLE
DAGSpec constructor should accept an Env object in the env parameter

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#403]
This doesn't work:

```python
from ploomber.spec import DAGSpec
from ploomber import with_env

@with_env('env.yaml')
def make(env):
    return DAGSpec('pipeline.yaml', env=env).to_dag()
```

But it should:

Here's the dagspec implementation:

https://github.com/ploomber/ploomber/blob/master/src/ploomber/spec/dagspec.py

- [ ] Implement change
- [ ] implement tests
- [ ] update example in projects that calls with `env=dict(env)`

**Comment by idomic** [comment]
@arturomf94 That can be another interesting story if you're up for the challenge :)

**Comment by arturomf94** [comment]
> @arturomf94 That can be another interesting story if you're up for the challenge :)

yeah! for sure! please assign this to me :)

**Comment by edublancas** [comment]
How to reproduce this:

```python
# run.py
from ploomber.spec import DAGSpec
from ploomber import with_env

@with_env('env.yaml')
def make(env):
    return DAGSpec('pipeline.yaml', env=env).to_dag()

# error when calling the function
make()
```

```
ploomber examples -n templates/ml-basic -o test
cd test
echo 'value: key' > env.yaml
python run.py
```

Error:

```pytb
Traceback (most recent call last):
  File "/Users/Edu/Desktop/test/test/run.py", line 10, in <module>
    make()
  File "/Users/Edu/dev/ploomber/src/ploomber/env/decorators.py", line 131, in wrapper
    raise e
  File "/Users/Edu/dev/ploomber/src/ploomber/env/decorators.py", line 128, in wrapper
    res = fn(Env.load(), *args, **kwargs)
  File "/Users/Edu/Desktop/test/test/run.py", line 7, in make
    return DAGSpec('pipeline.yaml', env=env).to_dag()
  File "/Users/Edu/dev/ploomber/src/ploomber/spec/dagspec.py", line 199, in __init__
    self._init(data=data,
  File "/Users/Edu/dev/ploomber/src/ploomber/spec/dagspec.py", line 290, in _init
    self.env = EnvDict(env,
  File "/Users/Edu/dev/ploomber/src/ploomber/env/envdict.py", line 67, in __init__
    self._path_to_env) = load_from_source(source)
  File "/Users/Edu/dev/ploomber/src/ploomber/env/envdict.py", line 276, in load_from_source
    with open(str(source)) as f:
FileNotFoundError: [Errno 2] No such file or directory: "{'user': 'Edu', 'cwd': '/Users/Edu/Desktop/test/test', 'now': '2022-02-12T15:57:28.471625', 'root': '/Users/Edu/Desktop/test/test', 'here': '/Users/Edu/Desktop/test/test', 'value': 'key'}"
```

the problem is in the initialization of EnvDict (`env/envdict.py`), we should check if `source` has an attribute `_data` and if that attribute is an instance of EnvDict, then do `source = source._data`, then the next lines in the initialization will do the right thing.
