### ISSUE TITLE
telemetry edge cases

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#469]
We can publish the current version but let's take care of this for the next one.

1. breaks if config.yaml does not have a `stats_enabled` key (`/telemetry/telemetry.py", line 185`)
2. breaks if config.yaml is corrupted
3. breaks if uid.yaml does not have a uid key (`ploomber/telemetry/telemetry.py", line 157`)
4. breaks if uid.yaml is corrupted
5. breaks if uid key in uid.yaml is not a string

```
Traceback (most recent call last):
  File "/opt/conda/bin/ploomber", line 8, in <module>
    sys.exit(cmd_router())
  File "/opt/conda/lib/python3.9/site-packages/ploomber/cli/cli.py", line 140, in cmd_router
    telemetry.log_api("unsupported-api-call", metadata={'argv': sys.argv})
  File "/opt/conda/lib/python3.9/site-packages/ploomber/telemetry/telemetry.py", line 249, in log_api
    = validate_entries(event_id,
  File "/opt/conda/lib/python3.9/site-packages/ploomber/telemetry/telemetry.py", line 222, in validate_entries
    uid = validate_inputs.str_param(uid, "uid")
  File "/opt/conda/lib/python3.9/site-packages/ploomber/telemetry/validate_inputs.py", line 7, in str_param
    raise TypeError(f"TypeError: Variable not supported/wrong type: "
TypeError: TypeError: Variable not supported/wrong type: 1.1, uid, should be a str
(base) root@8010ad09961d:/#
```

**Comment by edublancas** [comment]
For the next iteration

    capture exit code (error or not)
    record error messages

**Comment by idomic** [comment]
@edublancas On the first 5 bullets, do we just wanna recreate it if those edge cases happen and add tests? 
Some are really edge of the edge, like 5 for instance.

**Comment by idomic** [comment]
Need to detect multiple envs like airflow, slurm, argo, kubeflow, kubernetes.

**Comment by idomic** [comment]
Closing as it's fixed.
