### ISSUE TITLE
Better error tracebacks when ploomber build fails

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#529]
When `ploomber build` fails due to an error, we raise chained exceptions:

```pytb
/Users/Edu/dev/ploomber/src/ploomber/spec/dagspec.py:336: UserWarning: The following placeholders are declared in the environment but unused in the spec: {'run_id'}
  warnings.warn('The following placeholders are declared in the '
Executing:  42%|█████████████████████████████████████████████                                                               | 5/12 [00:06<00:08,  1.24s/cell]
Building task 'fit': 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:25<00:00,  6.42s/it]
Traceback (most recent call last):
  File "/Users/Edu/dev/ploomber/src/ploomber/cli/io.py", line 35, in wrapper
    fn(**kwargs)
  File "/Users/Edu/dev/ploomber/src/ploomber/cli/build.py", line 69, in main
    report = dag.build(force=args.force, debug=args.debug)
  File "/Users/Edu/dev/ploomber/src/ploomber/dag/dag.py", line 482, in build
    report = callable_()
  File "/Users/Edu/dev/ploomber/src/ploomber/dag/dag.py", line 581, in _build
    raise build_exception
  File "/Users/Edu/dev/ploomber/src/ploomber/dag/dag.py", line 513, in _build
    task_reports = self._executor(dag=self,
  File "/Users/Edu/dev/ploomber/src/ploomber/executors/serial.py", line 139, in __call__
    raise DAGBuildError(str(exceptions_all))
ploomber.exceptions.DAGBuildError:
===================================================================== DAG build failed ======================================================================
------------------------- NotebookRunner: fit -> MetaProduct({'model': File('output/model.pickle'), 'nb': File('output/nb.html')}) --------------------------
----------------------------------------------------------- /Users/Edu/Desktop/nb-test/ml/fit.py ------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Edu/dev/ploomber/src/ploomber/tasks/notebook.py", line 520, in run
    pm.execute_notebook(str(tmp), str(path_to_out_ipynb),
  File "/Users/Edu/miniconda3/envs/ploomber/lib/python3.9/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/Users/Edu/miniconda3/envs/ploomber/lib/python3.9/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError:
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/3h/_lvh_w_x5g30rrjzb_xnn2j80000gq/T/ipykernel_25453/4096975414.py in <module>
----> 1 raise ValueError

ValueError:


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/Edu/dev/ploomber/src/ploomber/tasks/abc.py", line 563, in _build
    res = self._run()
  File "/Users/Edu/dev/ploomber/src/ploomber/tasks/abc.py", line 672, in _run
    self.run()
  File "/Users/Edu/dev/ploomber/src/ploomber/tasks/notebook.py", line 523, in run
    raise TaskBuildError('An error occurred when calling'
ploomber.exceptions.TaskBuildError: An error occurred when calling papermil.execute_notebook, partially executed notebook with traceback available at /Users/Edu/Desktop/nb-test/ml/output/nb.ipynb

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/Edu/dev/ploomber/src/ploomber/executors/serial.py", line 188, in catch_exceptions
    fn()
  File "/Users/Edu/dev/ploomber/src/ploomber/executors/serial.py", line 161, in __call__
    return self.fn(**self.kwargs)
  File "/Users/Edu/dev/ploomber/src/ploomber/executors/serial.py", line 168, in catch_warnings
    result = fn()
  File "/Users/Edu/dev/ploomber/src/ploomber/executors/serial.py", line 161, in __call__
    return self.fn(**self.kwargs)
  File "/Users/Edu/dev/ploomber/src/ploomber/executors/serial.py", line 249, in build_in_subprocess
    report, meta = task._build(**build_kwargs)
  File "/Users/Edu/dev/ploomber/src/ploomber/tasks/abc.py", line 582, in _build
    raise TaskBuildError(msg) from e
ploomber.exceptions.TaskBuildError: Error building task "fit"
===================================================================== Summary (1 task) ======================================================================
NotebookRunner: fit -> MetaProduct({'model': File('output/model.pickle'), 'nb': File('output/nb.html')})
===================================================================== DAG build failed ======================================================================

```

That's way too long. We should remove unnecessary details (our chained exceptions) and print something like this: 

```pytb
/Users/Edu/dev/ploomber/src/ploomber/spec/dagspec.py:336: UserWarning: The following placeholders are declared in the environment but unused in the spec: {'run_id'}
  warnings.warn('The following placeholders are declared in the '
Executing:  42%|█████████████████████████████████████████████                                                               | 5/12 [00:06<00:08,  1.24s/cell]
Building task 'fit': 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:25<00:00,  6.42s/it]
Traceback (most recent call last):
ploomber.exceptions.DAGBuildError:
===================================================================== DAG build failed ======================================================================
------------------------- NotebookRunner: fit -> MetaProduct({'model': File('output/model.pickle'), 'nb': File('output/nb.html')}) --------------------------
----------------------------------------------------------- /Users/Edu/Desktop/nb-test/ml/fit.py ------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Edu/dev/ploomber/src/ploomber/tasks/notebook.py", line 520, in run
    pm.execute_notebook(str(tmp), str(path_to_out_ipynb),
  File "/Users/Edu/miniconda3/envs/ploomber/lib/python3.9/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/Users/Edu/miniconda3/envs/ploomber/lib/python3.9/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError:
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/3h/_lvh_w_x5g30rrjzb_xnn2j80000gq/T/ipykernel_25453/4096975414.py in <module>
----> 1 raise ValueError

ValueError:

ploomber.exceptions.TaskBuildError: An error occurred when calling papermil.execute_notebook, partially executed notebook with traceback available at /Users/Edu/Desktop/nb-test/ml/output/nb.ipynb
ploomber.exceptions.TaskBuildError: Error building task "fit"
===================================================================== Summary (1 task) ======================================================================
NotebookRunner: fit -> MetaProduct({'model': File('output/model.pickle'), 'nb': File('output/nb.html')})
===================================================================== DAG build failed ======================================================================

```

**Comment by edublancas** [comment]
fixed in 0.16
