### ISSUE TITLE
Networkx version issue

### ISSUE THREAD

**Issue by maticortesr** [ploomber/ploomber#535]
I fixed this issue on my machine but decided to open an issue before sending a PR out of the blue. This has happened to me in both MacOS and Fedora.

Error:
```sh
➜ ploomber examples -n templates/ml-basic -o ml-basic
Traceback (most recent call last):
  File "/home/matias/miniconda3/bin/ploomber", line 6, in <module>
    from ploomber.cli.cli import cmd_router
  File "/home/matias/miniconda3/lib/python3.9/site-packages/ploomber/__init__.py", line 2, in <module>
    from ploomber.dag.dag import DAG
  File "/home/matias/miniconda3/lib/python3.9/site-packages/ploomber/dag/dag.py", line 72, in <module>
    import networkx as nx
  File "/home/matias/miniconda3/lib/python3.9/site-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/home/matias/miniconda3/lib/python3.9/site-packages/networkx/generators/__init__.py", line 14, in <module>
    from networkx.generators.intersection import *
  File "/home/matias/miniconda3/lib/python3.9/site-packages/networkx/generators/intersection.py", line 13, in <module>
    from networkx.algorithms import bipartite
  File "/home/matias/miniconda3/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 16, in <module>
    from networkx.algorithms.dag import *
  File "/home/matias/miniconda3/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 23, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/home/matias/miniconda3/lib/python3.9/fractions.py)
```
The fix is just updating networkx to 2.5 or more as described here: https://stackoverflow.com/questions/66174862/import-error-cant-import-name-gcd-from-fractions

Might be worth updating the setup.py file to set a minimum version for networkx, happy to send a fix if this sounds good.

**Comment by edublancas** [comment]
thanks for investigating this issue, please submit a PR
