### ISSUE TITLE
Partial build fails - TypeError: cannot pickle 'module' object

### ISSUE THREAD

**Issue by reesehopkins** [ploomber/ploomber#584]
I see the following error when I do `ploomber build -p train`, but do not get the error when running `ploomber build`. My guess it that it relates to a joblib.dump. I tried to add custom un/serializers after seeing the error, but that did not fix it. Sorry, the pipeline is a bit complicated at this point and the error is hard to generate a easy to reproduce example for testing.

```python
Traceback (most recent call last):
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/site-packages/ploomber/cli/io.py", line 34, in wrapper
    fn(**kwargs)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/site-packages/ploomber/cli/build.py", line 49, in main
    report = dag.build_partially(args.partially,
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/site-packages/ploomber/dag/dag.py", line 667, in build_partially
    dag_copy = deepcopy(self)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/hydrates/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'module' object
```

**Comment by edublancas** [comment]
thanks for reporting this!

[the problem is here](https://github.com/ploomber/ploomber/blob/e9e8814c4f2a03d0a5294c4dba1189527a8fd69c/src/ploomber/dag/dag.py#L680), when using the `-p` argument, we need to create a copy of the DAG object (DAG is the object ploomber uses to represent your pipeline internally).

So I can confirm the problem *is not* with joblib.

To help me find where's the issue, please run this:

```python
from copy import deepcopy

for attr in (attr for attr in dir(dag) if not attr.startswith('_')):
    print(f'copying {attr}')  
    try:
        deepcopy(getattr(dag, attr))
    except Exception as e:
       print(f'failed to copy {attr}: {str(e)}')
```

and share the output

**Comment by edublancas** [comment]
Based on the output. My guess is that one of your database clients has a reference to a module object. Something like this:

```python
from ploomber.clients import DBAPIClient
import some_module

def get_client():
    # some_module is a module and doesn't work with pickle
    return DBAPIClient(some_module, dict(key='value'))
```

To test it, please create instances of your db clients and try to pickle them:

```python
import pickle
client = function_that_returns_client()
# this should throw the same error
pickle.dumps(client)
```

If this is the cause, we can fix it by allowing `DBAPIClient` to take a string with the module name:

```python
from ploomber.clients import DBAPIClient
import some_module

def get_client():
    # passing module name instead of the actual module object
    return DBAPIClient('module_name', dict(key='value'))
```

Let me know so we can add this to the backlog for the next release.

**Comment by edublancas** [comment]
This looks like a different error. The original one was about pickling a module object, this one is about pickling an object defined in the local scope.

Does `client.atdb()` return an object of type `DBClient`?

**Comment by reesehopkins** [comment]
No, it returns `sqlalchemy.engine.base.Connection` . One of  the problems is that our in-house library to connect to our databases is not DBAPI 2.0 compliant -- which I'd like to fix - but that's going to take some time.

**Comment by edublancas** [comment]
Ah ok. So most likely there is some logic inside that function that returns the `sqlalchemy.engine.base.Connection` which is referencing some module, hence, it fails to copy. Unfortunately, there isn't much we can do without looking at the code.

In any case, I opened #645, a shallow copy of the DAG may be enough, and if that's the case, we'd be able to solve the problem

**Comment by edublancas** [comment]
the conclusion from here is that it's the user's implementation what's causing the non-pickable error. closing it for now, but feel free to re-open it if you need more help!

**Comment by reesehopkins** [comment]
@edublancas, agreed. Best course of action is for me to refractor my code.

**Comment by reesehopkins** [comment]
@edublancas, reopening as I finally refactored the code. Running into the a similar error when doing a partial build. I think it has to do with how deepcopy/pickling handles modules (ref [stackoverlfow](https://stackoverflow.com/a/58040845)). I think #677 tried to address this, but it doesn't work in version `0.21`.

Here's some sample code.

```yaml
tasks:
  - source: 'query.sql'
    product: 'data.parquet'
    client: cpyai.ATDB # this is the refactored library for connecting to our databases
    chunksize: null
```

```python
(well-test-quality-2022) [hopkir@hotclw2106 well-test-quality]$ ploomber build -p calculate_signature
Loading pipeline...
/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/site-packages/ploomber/spec/dagspec.py:390: 

Traceback (most recent call last):
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/site-packages/ploomber/dag/dag.py", line 715, in _deepcopy_safe
    return deepcopy(self)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/anaconda3/envs/well-test-quality-2022/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'module' object
```

The previous error was `TypeError: cannot pickle '_thread.lock' object`

Here's the `__dict__` from the `cpyai.ATDB` object

```python

{'engine': Engine(oracle+cx_oracle:XXXXX),
 'dialect': <sqlalchemy.dialects.oracle.cx_oracle.OracleDialect_cx_oracle at 0x7fb4db71e7c0>,
 '_Connection__branch_from': None,
 '_dbapi_connection': <sqlalchemy.pool.base._ConnectionFairy at 0x7fb4daf6af70>,
 '_transaction': None,
 '_nested_transaction': None,
 '_Connection__savepoint_seq': 0,
 '_Connection__in_begin': False,
 'should_close_with_result': False,
 '_Connection__can_reconnect': True,
 '_echo': False,
 'dispatch': <sqlalchemy.event.base.JoinedConnectionEventsDispatch at 0x7fb4daf34d40>,
 '_has_events': False,
 '_execution_options': immutabledict({})}
```

FWIW, `cpyai.ATDB` is a subclass of `sqlalchemy.engine.base.Connection`.

**Comment by edublancas** [comment]
I think we can fix this by *not* copying the pipeline's clients. can you test this?

- change `client: cpyai.ATDB`  for another module that returns sone random object (e.g, `clients: clients.get_client`)

```python
# clients.py
def get_client():
    return object()
```

then re-run the partial build, let's see if this prevents the deepcopy error (of course this will fail since this isn't a valid client, but this means we got past the copying stage).

I'm still unsure of why this is trying to copy a module object, can you spot a module object in the `cpyai.ATDB` `__dict__`?

**Comment by reesehopkins** [comment]
Thanks for looking at this. I get this:

```
AttributeError: 'object' object has no attribute 'close'
```
My guess is that it's one of the SQlAlchemy modules - `dialect, dispatch, or pool`.

**Comment by edublancas** [comment]
ok, so I remember one of the sol

**Comment by edublancas** [comment]
ok, so I think the best solution here is to implement a custom method that does not copy the clients in the dag. I'll work on a quick fix and update you here!

**Comment by edublancas** [comment]
alright, I think i got it. can you try installing from the deepcopy branch and let me know if it works?

```
pip uninstall ploomber
pip install https://github.com/ploomber/ploomber@deepcopy
```

**Comment by reesehopkins** [comment]
Thanks for working this! Unfortunately, it resulted in an error again.

```python
(well-test-quality-8bN19svQ-py3.8) hopkir@ANC-WX740501173:~/well-test-quality$ ploomber build -p minute_data
Loading pipeline...
There's a new ploomber version available (0.21), you're running 0.21.1dev. To upgrade: pip install ploomber --upgrade
/home/hopkir/.cache/pypoetry/virtualenvs/well-test-quality-8bN19svQ-py3.8/lib/python3.8/site-packages/ploomber/spec/dagspec.py:390: UserWarning: The following placeholders are declared in the environment but unused in the spec: {'start_date', 'bub_id', 'experiment_name', 'signature_data', 'end_date', 'column_order', 'drillsites', 'welltest_data', 'choke_corr_cols'}
  warnings.warn('The following placeholders are declared in the '
Traceback (most recent call last):
  File "/home/hopkir/.cache/pypoetry/virtualenvs/well-test-quality-8bN19svQ-py3.8/lib/python3.8/site-packages/ploomber/dag/dag.py", line 718, in _deepcopy_safe
    copy = deepcopy(self)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/hopkir/.pyenv/versions/3.8.10/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'module' object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hopkir/.cache/pypoetry/virtualenvs/well-test-quality-8bN19svQ-py3.8/lib/python3.8/site-packages/ploomber/cli/io.py", line 53, in wrapper
    fn(**kwargs)
  File "/home/hopkir/.cache/pypoetry/virtualenvs/well-test-quality-8bN19svQ-py3.8/lib/python3.8/site-packages/ploomber_core/telemetry/telemetry.py", line 529, in wrapper
    raise e
  File "/home/hopkir/.cache/pypoetry/virtualenvs/well-test-quality-8bN19svQ-py3.8/lib/python3.8/site-packages/ploomber_core/telemetry/telemetry.py", line 515, in wrapper
    result = func(_payload, *args, **kwargs)
  File "/home/hopkir/.cache/pypoetry/virtualenvs/well-test-quality-8bN19svQ-py3.8/lib/python3.8/site-packages/ploomber/cli/build.py", line 84, in main
    report = dag.build_partially(args.partially,
  File "/home/hopkir/.cache/pypoetry/virtualenvs/well-test-quality-8bN19svQ-py3.8/lib/python3.8/site-packages/ploomber/dag/dag.py", line 777, in build_partially
    dag_copy = self._deepcopy_safe()
  File "/home/hopkir/.cache/pypoetry/virtualenvs/well-test-quality-8bN19svQ-py3.8/lib/python3.8/site-packages/ploomber/dag/dag.py", line 720, in _deepcopy_safe
    raise RuntimeError(
RuntimeError: An error occurred while copying DAG object
```

**Comment by edublancas** [comment]
Ok, I pushed a changed; I'm skipping copying the DAG altogether. it should work now if you execute the partial build from the CLI, which I think is what you're using. let me know if it works:

```
pip uninstall ploomber
pip install https://github.com/ploomber/ploomber@deepcopy
```
