### ISSUE TITLE
ml-basic fails on windows when converting to HTML

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#595]
I've seen this a few times. nbconvert fails on windows sometimes, I haven't found a solution yet. The benefit of the HTML is that users can run the ml-basic example and then open the HTML report, but we don't want windows users to have a broken example 

```pytb
Traceback (most recent call last):
  File "c:\dev\python\contrib\ploomber\src\ploomber\tasks\abc.py", line 561, in _build
    res = self._run()
  File "c:\dev\python\contrib\ploomber\src\ploomber\tasks\abc.py", line 670, in _run
    self.run()
  File "c:\dev\python\contrib\ploomber\src\ploomber\tasks\notebook.py", line 573, in run
    self._converter.convert()
  File "c:\dev\python\contrib\ploomber\src\ploomber\tasks\notebook.py", line 139, in convert
    self._from_ipynb(self._path_to_output, self._exporter,
  File "c:\dev\python\contrib\ploomber\src\ploomber\tasks\notebook.py", line 195, in _from_ipynb
    path.write_text(content)
  File "c:\program files\python38\lib\pathlib.py", line 1256, in write_text
    return f.write(data)
  File "c:\program files\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ue6c6' in position 237531: character maps to <undefined>
```

**Comment by edublancas** [comment]
temporary measure: reverted task to `.ipynb`
