### ISSUE TITLE
installing ploomber yields to an old click version

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#707]
users have reported that installing ploomber is broken with the following error:

```pytb
(python) C:\Users\yosty\Desktop\Desktop_Folder\14 - git\dataScripts\EY-PDF>ploomber scaffold --empty
Traceback (most recent call last):
  File "C:\Users\yosty\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yosty\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\yosty\Envs\python\Scripts\ploomber.exe\__main__.py", line 4, in <module>
  File "c:\users\yosty\envs\python\lib\site-packages\ploomber_cli\cli.py", line 36, in <module>
    def cli():
  File "c:\users\yosty\envs\python\lib\site-packages\click\decorators.py", line 304, in decorator
    return option(*(param_decls or ("--version",)), **attrs)(f)
  File "c:\users\yosty\envs\python\lib\site-packages\click\decorators.py", line 192, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "c:\users\yosty\envs\python\lib\site-packages\click\core.py", line 1714, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'package_name'
```

This happens if `pip install ploomber` yields an old version of click (`7.x`), I'm not sure why this is happening. Currently, to solve it:

```sh
pip install click --upgrade
```

**Comment by idomic** [comment]
Important to say this happened on sagemaker

**Comment by edublancas** [comment]
closing this in favor of https://github.com/ploomber/ploomber/issues/719
