### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#870]
Maybe this is a windows only issue? I think this was introduced when we released the support for multiple output notebooks 

From slack:

By the way, https://github.com/ploomber/projects/tree/master/templates/ml-basic report an error after ploomber build:

`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ag10\lib\site-packages\nbformat\reader.py", line 18, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\ag10\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\envs\ag10\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\envs\ag10\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 192 column 411 (char 5665)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ag10\lib\site-packages\ploomber\tasks\abc.py", line 554, in _build
    res = self._run()
  File "C:\ProgramData\Anaconda3\envs\ag10\lib\site-packages\ploomber\tasks\abc.py", line 663, in _run
    self.run()
  File "C:\ProgramData\Anaconda3\envs\ag10\lib\site-packages\ploomber\tasks\notebook.py", line 833, in run
    self._converter.convert()
  File "C:\ProgramData\Anaconda3\envs\ag10\lib\site-packages\ploomber\tasks\notebook.py", line 199, in convert
    self._from_ipynb(self._path_to_output, self._exporter,
  File "C:\ProgramData\Anaconda3\envs\ag10\lib\site-packages\ploomber\tasks\notebook.py", line 254, in _from_ipynb
    nb = nbformat.reads(path.read_text(), as_version=nbformat.NO_CONVERT)
  File "C:\ProgramData\Anaconda3\envs\ag10\lib\site-packages\nbformat\__init__.py", line 88, in reads
    nb = reader.reads(s, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\ag10\lib\site-packages\nbformat\reader.py", line 72, in reads
    nb_dict = parse_json(s, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\ag10\lib\site-packages\nbformat\reader.py", line 21, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...") from e
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: '{\n "cells": [\n  {\n   "cell_type": "m...

ploomber.exceptions.TaskBuildError: Error building task "fit"
Found that there are related issues at github.`

Changing nb: output/nb.html to nb: output/nb.ipynb , it worked fine for me.

**Comment by idomic** [comment]
We'd want to fix this bug and add a test so we can capture errors like these in the CI next time.
