### ISSUE TITLE
Cannot load notebooks: ModuleNotFoundError: Error processing dotted path

### ISSUE THREAD

**Issue by lambdaofgod** [ploomber/ploomber#878]
I have a notebook folder in ploomber project and ploomber tries to run something so I can't even load the notebook (which BTW is not referenced in pipeline.yaml in any way)

What happened? How is it possible that ploomber breaks jupyter?

Error message

```
[I 11:59:22.671 NotebookApp] [Ploomber] Requested model: work/wwf/notebooks/Enrich_Test.ipynb. Looking for DAG with root dir: /home/kuba/Projects                            
[E 11:59:22.786 NotebookApp] Uncaught exception GET /api/contents/work/wwf/notebooks/Enrich_Test.ipynb?type=notebook&_=1656064762442 (127.0.0.1)                             
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/work/wwf/notebooks/Enrich_Test.ipynb?type=notebook&_=1656064762442', version='
HTTP/1.1', remote_ip='127.0.0.1')                                                                                                                                            
    Traceback (most recent call last):                                                                                                                                       
      File "/home/kuba/.local/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute                                                                            
        result = await result                                                                                                                                                
      File "/home/kuba/.local/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper                                                                              
        yielded = ctx_run(next, result)                                                                                                                                      
      File "/home/kuba/.local/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 118, in get                                                          
        model = yield maybe_future(self.contents_manager.get(                  
      File "/home/kuba/.local/lib/python3.8/site-packages/ploomber/jupyter/manager.py", line 267, in get                                                                     
        self.load_dag(                                                                                                                                                       
      File "/home/kuba/.local/lib/python3.8/site-packages/ploomber/jupyter/manager.py", line 193, in load_dag                                                                
        pairs = [(resolve_path(                                                       
      File "/home/kuba/.local/lib/python3.8/site-packages/ploomber/jupyter/manager.py", line 196, in <listcomp>                                                                      if t.source.loc is not None]                                                  
      File "/home/kuba/.local/lib/python3.8/site-packages/ploomber/sources/pythoncallablesource.py", line 130, in loc                                                        
        self._loc = self._callable_loader.get_loc()                                                                                                                          
      File "/home/kuba/.local/lib/python3.8/site-packages/ploomber/sources/pythoncallablesource.py", line 58, in get_loc                                                     
        loc, _ = lazily_locate_dotted_path(self._primitive)                                                                                                                        File "/home/kuba/.local/lib/python3.8/site-packages/ploomber/util/dotted_path.py", line 343, in lazily_locate_dotted_path                                              
        raise ModuleNotFoundError('Error processing dotted '
    ModuleNotFoundError: Error processing dotted path 'deepsense_wwf.data_utils.copy_zipped_data': 'deepsense_wwf' appears to be a namespace package, which are not supported
[W 11:59:22.790 NotebookApp] Unhandled error          
[E 11:59:22.791 NotebookApp] {                                                                                                                                               
      "Host": "localhost:8888",                                                                                                                                              
      "Accept": "application/json, text/javascript, */*; q=0.01",                                                                                                            
      "Referer": "http://localhost:8888/notebooks/work/wwf/notebooks/Enrich_Test.ipynb",                                                                                     
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"                                                                         
    }                                                          
```

**Comment by lambdaofgod** [comment]
Thanks, it worked for jupyter notebook but *not for jupyterlab*

I disabled it for jupyterlab, and when I run `jupyter labextension list` I don't see ploomber, but it still loads when I run jupyter lab.

The funny part is I don't even remember installing ploomber extension...

**Comment by lambdaofgod** [comment]
Wouldn't disabling automatic installation of the extension basically solve the problem? I would prefer to have the option to install the extension myself, and temporarily the biggest problem will go away

I didn't even know that I had this extension until it failed :smile:

**Comment by edublancas** [comment]
good point. the problem is that if the extension doesn't enable automatically, then most people will never find it. so I think it's best to have it turned on but we should ensure it doesn't break Jupyter.

**Comment by edublancas** [comment]
I'm trying to debug this but I'm unable to reproduce it. Does `deepsense_wwf.data_utils.copy_zipped_data` in your `pipeline.yaml`? Or in any of them if you have more than one. It looks like the extension it's trying to load it since it's part of a pipeline but is unable to find it.

**Comment by edublancas** [comment]
Yeah, I agree. We'll fix this as soon as possible. It's pretty bad that ploomber is breaking jupyter just because the pipeline isn't loading. I'll try to reproduce and follow up with more questions if needed

**Comment by edublancas** [comment]
@lambdaofgod can you install from git and let me know if the error persists?

```sh
pip uninstall ploomber -y
pip install git+https://github.com/ploomber/ploomber@master
```

**Comment by 94rain** [comment]
> Yeah, I agree. We'll fix this as soon as possible. It's pretty bad that ploomber is breaking jupyter just because the pipeline isn't loading. I'll try to reproduce and follow up with more questions if needed
> 
> Notes for when we fix this, the problem is when accessing `.source.loc`, it'll break if unable to find the source for the function in the `pipeline.yaml`
> 
> https://github.com/ploomber/ploomber/blob/6986b5f3f27b57ce9072e78a0472a89aa37206dc/src/ploomber/jupyter/manager.py#L199
> 
> , we need a try catch there

How should we handle the exception in the `except` clause? Assigning an empty list to `pairs = []`?

**Comment by edublancas** [comment]
what we want if the `load_dag` fails to execute is for Jupyter to work appropriately

**Comment by lambdaofgod** [comment]
I can confirm this is fixed. Thanks!

**Comment by idomic** [comment]
@lambdaofgod feel free posting our delivery speed in socials 2 weeks from bug to production  😁🙌

**Comment by edublancas** [comment]
[Click here to tweet something nice.](https://twitter.com/intent/tweet?text=Check out @Ploomber they are amazing!&url=https://github.com/ploomber/ploomber)
